// stylelint.config.js
/** @type {import('stylelint').Config} */
export default {
    extends: ['stylelint-config-standard'],
    plugins: ['stylelint-order'],
    rules: {
        // Убираем дублирующиеся свойства
        'declaration-block-no-duplicate-properties': true,

        // Только проверка порядка, без автоформатирования
        'order/properties-order': [
            {
                groupName: 'Позиционирование',
                properties: ['position', 'top', 'right', 'bottom', 'left', 'z-index'],
            },
            {
                groupName: 'Блочная модель',
                properties: [
                    'display',
                    'overflow',
                    'overflow-x',
                    'overflow-y',
                    'box-sizing',
                    'width',
                    'min-width',
                    'max-width',
                    'height',
                    'min-height',
                    'max-height',
                    'margin',
                    'margin-top',
                    'margin-right',
                    'margin-bottom',
                    'margin-left',
                    'padding',
                    'padding-top',
                    'padding-right',
                    'padding-bottom',
                    'padding-left',
                ],
            },
            {
                groupName: 'Флексбокс',
                properties: [
                    'flex',
                    'flex-basis',
                    'flex-direction',
                    'flex-flow',
                    'flex-grow',
                    'flex-shrink',
                    'flex-wrap',
                    'align-content',
                    'align-items',
                    'align-self',
                    'justify-content',
                    'order',
                    'gap',
                ],
            },
            {
                groupName: 'Типографика',
                properties: [
                    'color',
                    'font',
                    'font-family',
                    'font-size',
                    'font-style',
                    'font-weight',
                    'font-variant',
                    'letter-spacing',
                    'line-height',
                    'text-align',
                    'text-decoration',
                    'text-indent',
                    'text-overflow',
                    'text-rendering',
                    'text-shadow',
                    'text-transform',
                    'white-space',
                    'word-break',
                    'word-spacing',
                ],
            },
            {
                groupName: 'Визуальные свойства',
                properties: [
                    'background',
                    'background-color',
                    'background-image',
                    'background-position',
                    'background-repeat',
                    'background-size',
                    'border',
                    'border-color',
                    'border-radius',
                    'border-style',
                    'border-width',
                    'opacity',
                    'outline',
                    'box-shadow',
                    'visibility',
                ],
            },
            {
                groupName: 'Анимации',
                properties: [
                    'transition',
                    'transition-delay',
                    'transition-duration',
                    'transition-property',
                    'transition-timing-function',
                    'animation',
                    'animation-delay',
                    'animation-direction',
                    'animation-duration',
                    'animation-fill-mode',
                    'animation-iteration-count',
                    'animation-name',
                    'animation-play-state',
                    'animation-timing-function',
                    'transform',
                    'transform-origin',
                ],
            },
            {
                groupName: 'Прочее',
                properties: ['content', 'cursor', 'pointer-events', 'user-select'],
            },
        ],
    },
};
